"""接口形状（Pydantic）—— **契约的唯一来源**。

``contracts/schemas/*.json`` 由 :data:`EXPORTS` 导出，不要手改那些 JSON。
改完这里的模型后运行::

    python tools/export_contracts.py

并把生成物一起提交；测试会比对生成物是否过期。
"""

from __future__ import annotations

from app.schemas.exports import EXPORTS

from app.schemas.activation import ActivationResult, RedeemRequest, SessionState
from app.schemas.admin import (
    AdminSiteActionResult,
    AdminSiteItem,
    AdminSiteListPayload,
    AdminSiteOrderRequest,
    AdminStatusPayload,
    CacheStats,
    CacheTtl,
    CodeActionResult,
    CodeListItem,
    CodeListPayload,
    DeviceItem,
    DeviceListPayload,
    ExtendRequest,
    IssueCodesRequest,
    IssueCodesResult,
    KickResult,
    RefreshResult,
    SiteHealth,
    WarmupSiteResult,
    WarmupStatus,
)
from app.schemas.admin_site_control import (
    CategoryRuleItem,
    CrawlerCodePayload,
    CrawlerUploadRequest,
    CrawlerUploadResult,
    CrawlerValidateRequest,
    CrawlerValidateResult,
    ProxyEngineActionResponse,
    ProxyEngineStatusPayload,
    ProxyNodeBindRequest,
    ProxyNodeCreateRequest,
    ProxyNodeItem,
    ProxyNodeListPayload,
    ProxyTestRequest,
    ProxyTestResult,
    SiteAdvancedSettingPayload,
    SiteAdvancedSettingUpdateRequest,
    SiteCategoryRulePayload,
    SiteCategoryRuleUpdateRequest,
    SiteDetailPolicyPayload,
    SiteDetailPolicyUpdateRequest,
    SubCategoryItem,
)
from app.schemas.admin_extended import (
    AggregateSearchPayload,
    AggregateSearchSiteResult,
    CacheClearRequest,
    CacheClearResult,
    CacheEntryDetail,
    CacheKeyEntry,
    CachePreheatRequest,
    CachePreheatResult,
    CacheStatsPayload,
    CodeCleanupResult,
    ImageProxyClearResult,
    ImageProxyConfig,
    ImageProxyStats,
    PlaygroundProbeRequest,
    PlaygroundProbeResult,
    SamplePostersPayload,
    SiteCachePolicy,
    SitePreheatDetail,
    SystemMaintenancePayload,
    SystemNoticePayload,
    SystemStatusPayload,
    TestDecryptRequest,
    TestDecryptResult,
)
from app.schemas.catalog import DetailPayload, HomePayload, HomeSection, ListPayload
from app.schemas.envelope import Envelope, ErrorInfo
from app.schemas.episode import Episode, LineInfo
from app.schemas.playback import Playback
from app.schemas.site import SiteListPayload, SiteMeta
from app.schemas.system import HealthPayload
from app.schemas.vod import SubCategory, VodCategory, VodItem
from app.schemas.webhook import (
    TelegramVerifyRequest,
    TelegramVerifyResult,
    WebhookConfigPayload,
    WebhookDeliveryLogItem,
    WebhookLogsPayload,
    WebhookTestRequest,
    WebhookTestResult,
)
from app.modules.experience.schemas import (
    ClientBootstrapPayload,
    DraftSaveResult,
    ExperienceDraftPayload,
    ExperienceDraftUpdateRequest,
    ExperienceReleaseItem,
    PageViewModel,
    ReleaseCurrentPayload,
    ReleasePublishRequest,
    ReleasePublishResult,
    ReleaseRollbackRequest,
)

__all__ = [
    "EXPORTS",
    "ActivationResult",
    "AdminSiteActionResult",
    "AdminSiteItem",
    "AdminSiteListPayload",
    "AdminSiteOrderRequest",
    "AdminStatusPayload",
    "CacheStats",
    "CacheTtl",
    "CategoryRuleItem",
    "CodeActionResult",
    "CodeListItem",
    "CodeListPayload",
    "CrawlerCodePayload",
    "CrawlerUploadRequest",
    "CrawlerUploadResult",
    "CrawlerValidateRequest",
    "CrawlerValidateResult",
    "DetailPayload",
    "DeviceItem",
    "DeviceListPayload",
    "ExtendRequest",
    "IssueCodesRequest",
    "IssueCodesResult",
    "KickResult",
    "Envelope",
    "Episode",
    "ErrorInfo",
    "HealthPayload",
    "HomePayload",
    "HomeSection",
    "LineInfo",
    "ListPayload",
    "Playback",
    "RedeemRequest",
    "RefreshResult",
    "SessionState",
    "SiteAdvancedSettingPayload",
    "SiteAdvancedSettingUpdateRequest",
    "SiteCategoryRulePayload",
    "SiteCategoryRuleUpdateRequest",
    "SiteDetailPolicyPayload",
    "SiteDetailPolicyUpdateRequest",
    "SiteHealth",
    "SiteListPayload",
    "SiteMeta",
    "SubCategory",
    "SubCategoryItem",
    "VodCategory",
    "VodItem",
    "WarmupSiteResult",
    "WarmupStatus",
    # 扩展契约
    "AggregateSearchPayload",
    "AggregateSearchSiteResult",
    "CacheClearRequest",
    "CacheClearResult",
    "CacheKeyEntry",
    "CacheEntryDetail",
    "CachePreheatRequest",
    "CachePreheatResult",
    "SitePreheatDetail",
    "CacheStatsPayload",
    "ImageProxyClearResult",
    "ImageProxyStats",
    "SamplePostersPayload",
    "PlaygroundProbeRequest",
    "PlaygroundProbeResult",
    "SiteCachePolicy",
    "SystemMaintenancePayload",
    "SystemNoticePayload",
    "SystemStatusPayload",
    "CodeCleanupResult",
    "ImageProxyConfig",
    "ProxyNodeItem",
    "ProxyNodeListPayload",
    "ProxyNodeCreateRequest",
    "ProxyTestRequest",
    "ProxyTestResult",
    "ProxyNodeBindRequest",
    "ProxyEngineStatusPayload",
    "ProxyEngineActionResponse",
    "TestDecryptRequest",
    "TestDecryptResult",
    "ClientBootstrapPayload",
    "ReleaseCurrentPayload",
    "PageViewModel",
    "ExperienceDraftPayload",
    "ExperienceDraftUpdateRequest",
    "DraftSaveResult",
    "ExperienceReleaseItem",
    "ReleasePublishRequest",
    "ReleasePublishResult",
    "ReleaseRollbackRequest",
    "WebhookConfigPayload",
    "WebhookLogsPayload",
    "WebhookTestRequest",
    "WebhookTestResult",
    "TelegramVerifyRequest",
    "TelegramVerifyResult",
    "WebhookDeliveryLogItem",
]
